-- Generated by nwg-displays on 2026-08-09 at 14:19:28. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1920@120.0",
    position = "3852x137",
    scale = 2.0
})
hl.monitor({
    output = "DP-4",
    mode = "1920x1080@60.0",
    position = "1932x137",
    scale = 1.0,
    -- mirror = "eDP-1"
})
